USE [master]
GO

/****** Object:  Database [EMMS]    Script Date: 28/10/2024 11:59:47 ******/
CREATE DATABASE [EMMS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'loanInfo', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\EMMS.mdf' , SIZE = 26624KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'loanInfo_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\EMMS_1.ldf' , SIZE = 470144KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [EMMS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [EMMS] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [EMMS] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [EMMS] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [EMMS] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [EMMS] SET ARITHABORT OFF 
GO

ALTER DATABASE [EMMS] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [EMMS] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [EMMS] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [EMMS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [EMMS] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [EMMS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [EMMS] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [EMMS] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [EMMS] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [EMMS] SET  DISABLE_BROKER 
GO

ALTER DATABASE [EMMS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [EMMS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [EMMS] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [EMMS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [EMMS] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [EMMS] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [EMMS] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [EMMS] SET RECOVERY FULL 
GO

ALTER DATABASE [EMMS] SET  MULTI_USER 
GO

ALTER DATABASE [EMMS] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [EMMS] SET DB_CHAINING OFF 
GO

ALTER DATABASE [EMMS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [EMMS] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [EMMS] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [EMMS] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [EMMS] SET QUERY_STORE = OFF
GO

ALTER DATABASE [EMMS] SET  READ_WRITE 
GO

